# Generate CMAKE_INSTALL_<DIR> etc...
function(set_install_dirs)
    # Don't set this var! https://cmake.org/cmake/help/latest/command/install.html#installing-files
    if (NOT DEFINED CMAKE_INSTALL_DATAROOTDIR)
        set(CMAKE_INSTALL_DATAROOTDIR share CACHE PATH "Read-only architecture-independent data root (share)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_INCLUDEDIR)
        set(CMAKE_INSTALL_INCLUDEDIR include CACHE PATH "C/C++ header files (include)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_BINDIR)
        set(CMAKE_INSTALL_BINDIR bin CACHE PATH "User executables (bin)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_SBINDIR)
        set(CMAKE_INSTALL_SBINDIR sbin CACHE PATH "System admin executables (sbin)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_LIBDIR)
        set(CMAKE_INSTALL_LIBDIR lib CACHE PATH "Object code libraries (lib)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_LIBEXECDIR)
        set(CMAKE_INSTALL_LIBEXECDIR libexec CACHE PATH "Program executables (libexec)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_SHAREDSTATEDIR)
        set(CMAKE_INSTALL_SHAREDSTATEDIR com CACHE PATH "Modifiable architecture-independent data (com)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_DATADIR)
        set(CMAKE_INSTALL_DATADIR ${CMAKE_INSTALL_DATAROOTDIR} CACHE PATH "Read-only architecture-independent data (DATAROOTDIR)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_LOCALSTATEDIR)
        set(CMAKE_INSTALL_LOCALSTATEDIR var CACHE PATH "Modifiable single-machine data (var)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_SYSCONFDIR)
        set(CMAKE_INSTALL_SYSCONFDIR etc CACHE PATH "Read-only single-machine data (etc)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_RUNSTATEDIR)
        set(CMAKE_INSTALL_RUNSTATEDIR ${CMAKE_INSTALL_LOCALSTATEDIR}/run CACHE PATH "Run-time variable data (LOCALSTATEDIR/run)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_LOCALEDIR)
        set(CMAKE_INSTALL_LOCALEDIR ${CMAKE_INSTALL_DATAROOTDIR}/locale CACHE PATH "Locale-dependent data (DATAROOTDIR/locale)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_DOCDIR)
        set(CMAKE_INSTALL_DOCDIR ${CMAKE_INSTALL_DATAROOTDIR}/doc/${PROJECT_NAME} CACHE PATH "Documentation root (DATAROOTDIR/doc/PROJECT_NAME)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_INFODIR)
        set(CMAKE_INSTALL_INFODIR ${CMAKE_INSTALL_DATAROOTDIR}/info CACHE PATH "Info documentation (DATAROOTDIR/info)")
    endif ()
    if (NOT DEFINED CMAKE_INSTALL_MANDIR)
        set(CMAKE_INSTALL_MANDIR ${CMAKE_INSTALL_DATAROOTDIR}/man CACHE PATH "Man documentation (DATAROOTDIR/man)")
    endif ()
    # get access to helper functions for creating config files
    include(GNUInstallDirs)
endfunction()
set_install_dirs()
